# Site settings
title: come az u(a)re | A blog on things azure
description: "A minimal blog site with tips and tricks on Azure"
url: "http://blog.yogimonkey.ooo"
author:
  name: "Ameet Konnur"
  email: "ameetk@live.in"
  url: ""

# Build settings
baseurl: /blogs # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
